# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-10 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flaskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_source',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='usa_tracking',
            field=models.CharField(max_length=255),
        ),
    ]
