# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-10 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flaskapp', '0002_auto_20170910_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='procurement_date',
            field=models.DateTimeField(),
        ),
    ]
